---
- name: Attach ASM Policy to Virtual Server
  hosts: all
  connection: local

  tasks:
      - name: include Variables
        include_vars: 'myVariables.yaml'
        
      - name: GET ASM POLICY ID
        f5_asm_getPolicyID:
            server: "{{ inventory_hostname }}"
            user: "{{ bigip_username }}"
            password: "{{ bigip_password }}"
            policyName: "asm_tested_{{ appName }}"
            validate_certs: "{{ validate_certs }}"
        register: policyId
#        no_log: true

      - name: ATTACH TO VS
        f5_asm_attachtoVS:
            partition: "Common"
            server: "{{ inventory_hostname }}"
            virtual: "{{ appName }}_vs"
            policyId: "{{ policyId.policyId }}"
            user: "{{ bigip_username }}"
            password: "{{ bigip_password }}"
            validate_certs: "{{ validate_certs }}"
