---
- name: Deploy a new Service
  hosts: all
  connection: local

  tasks:
      - name: include Variables
        include_vars: 'myVariables.yaml'

      - name: Create an ASM Policy based on a Template and apply it to a VS
        f5_asmPolicy:
            connection: "rest"
            server: "{{ inventory_hostname }}"
            user: "{{ bigip_username }}"
            password: "{{ bigip_password }}"
            partition: "{{ partition }}"
            name: "{{appName}}_asm"
            description: "This is an ASM Policy created automatically based on RDP"
            virtual: "{{appName}}_vs"
            lang: "utf-8"
            enforcementMode: "blocking"

      - name: get ID
        f5_asm_getPolicyID:
            server: "{{ inventory_hostname }}"
            user: "{{ bigip_username }}"
            password: "{{ bigip_password }}"
            policyName: "{{ appName }}_asm"
            validate_certs: "{{ validate_certs }}"
        register: policyId

      - name: Force Learning of URLs
        f5_asm_learnURLS:
            server: "{{ inventory_hostname }}"
            user: "{{ bigip_username }}"
            password: "{{ bigip_password }}"
            policyId: "{{ policyId.policyId }}”

